application: magdaandjavi
version: 18
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: "2.6"

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: wedding.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

- url: /static/build/[^/]+
  static_dir: static/build/
  expiration: '365d'
  secure: always

- url: /static/src/
  static_dir: static/src/
  expiration: '365d'
  secure: always

- url: /static/email/
  static_dir: static/email/
  expiration: '365d'
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: wedding.wsgi.application
  secure: always
  login: admin

- url: /cms.*
  script: wedding.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: wedding.wsgi.application
  secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - \.storage.*
  - (.*)\.pyc
  - ^manage\.py$
  - ^README\.md$
  - ^(deploy|installdeps|runtests)\.sh$
  - ^requirements\.txt$
  - install_deps
  - sitepackages/google_appengine*
  - ^lib/(.*)-info$
  - ^node_modules/*
  - ^static/src/*
  - ^sitepackages-dev/*
